name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
    - uses: actions/checkout@v2
    - name: Analising source code
      run: find ./src/ ./tests/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: PhpCS
      run: ./vendor/bin/phpcs
    - name: Psalm
      run: ./vendor/bin/psalm --show-info=false
    - name: PhpUnit
      run: ./vendor/bin/phpunit
